/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonDashboardRouteImport } from './routes/pokemon-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonDetailsNameRouteImport } from './routes/pokemon-details.$name'

const PokemonDashboardRoute = PokemonDashboardRouteImport.update({
  id: '/pokemon-dashboard',
  path: '/pokemon-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonDetailsNameRoute = PokemonDetailsNameRouteImport.update({
  id: '/pokemon-details/$name',
  path: '/pokemon-details/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pokemon-dashboard': typeof PokemonDashboardRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pokemon-dashboard': typeof PokemonDashboardRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pokemon-dashboard': typeof PokemonDashboardRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/pokemon-dashboard' | '/pokemon-details/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/pokemon-dashboard' | '/pokemon-details/$name'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pokemon-dashboard'
    | '/pokemon-details/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PokemonDashboardRoute: typeof PokemonDashboardRoute
  PokemonDetailsNameRoute: typeof PokemonDetailsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon-dashboard': {
      id: '/pokemon-dashboard'
      path: '/pokemon-dashboard'
      fullPath: '/pokemon-dashboard'
      preLoaderRoute: typeof PokemonDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon-details/$name': {
      id: '/pokemon-details/$name'
      path: '/pokemon-details/$name'
      fullPath: '/pokemon-details/$name'
      preLoaderRoute: typeof PokemonDetailsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PokemonDashboardRoute: PokemonDashboardRoute,
  PokemonDetailsNameRoute: PokemonDetailsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
